package dev.partemy.zmeuai.app.ui.theme
import androidx.compose.ui.graphics.Color

internal object ZmeuaiColors {

    val primaryLight = Color(0xFF612A74)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF723A84)
    val onPrimaryContainerLight = Color(0xFFFFEDFE)
    val secondaryLight = Color(0xFF894F3C)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFF3A992)
    val onSecondaryContainerLight = Color(0xFF4E2011)
    val tertiaryLight = Color(0xFF763E56)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFA0627B)
    val onTertiaryContainerLight = Color(0xFFFFFFFF)
    val errorLight = Color(0xFF972236)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFC94757)
    val onErrorContainerLight = Color(0xFFFFFFFF)
    val backgroundLight = Color(0xFFF3EEE9)
    val onBackgroundLight = Color(0xFF1F1A1F)
    val surfaceLight = Color(0xFFFDF8F7)
    val onSurfaceLight = Color(0xFF1C1B1B)
    val surfaceVariantLight = Color(0xFF776F69)
    val onSurfaceVariantLight = Color(0xFF4D4540)
    val outlineLight = Color(0xFF7E756F)
    val outlineVariantLight = Color(0xFFD0C4BD)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF313030)
    val inverseOnSurfaceLight = Color(0xFFF4F0EF)
    val inversePrimaryLight = Color(0xFFEFB0FF)
    val surfaceDimLight = Color(0xFFDDD9D8)
    val surfaceBrightLight = Color(0xFFFDF8F7)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF7F3F1)
    val surfaceContainerLight = Color(0xFFF1EDEC)
    val surfaceContainerHighLight = Color(0xFFEBE7E6)
    val surfaceContainerHighestLight = Color(0xFFE6E2E0)

    val primaryDark = Color(0xFFDF9ECD)
    val onPrimaryDark = Color(0xFF002E69)
    val primaryContainerDark = Color(0xFF58216B)
    val onPrimaryContainerDark = Color(0xFFF1B7FF)
    val secondaryDark = Color(0xFFFFC8B8)
    val onSecondaryDark = Color(0xFF512313)
    val secondaryContainerDark = Color(0xFFE19A83)
    val onSecondaryContainerDark = Color(0xFF3D1406)
    val tertiaryDark = Color(0xFFFCB2CD)
    val onTertiaryDark = Color(0xFF511F36)
    val tertiaryContainerDark = Color(0xFF9A5D75)
    val onTertiaryContainerDark = Color(0xFFFFFFFF)
    val errorDark = Color(0xFFFFB2B6)
    val onErrorDark = Color(0xFF67001A)
    val errorContainerDark = Color(0xFFC04151)
    val onErrorContainerDark = Color(0xFFFFFFFF)
    val backgroundDark = Color(0xFF0A0A0A)
    val onBackgroundDark = Color(0xFFEAE0E7)
    val surfaceDark = Color(0xFF171B23)
    val onSurfaceDark = Color(0xFFE3E2E6)
    val surfaceVariantDark = Color(0xFF7A808C)
    val onSurfaceVariantDark = Color(0xFFC4C6D0)
    val outlineDark = Color(0xFF998F88)
    val outlineVariantDark = Color(0xFF4D4540)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE6E2E0)
    val inverseOnSurfaceDark = Color(0xFF313030)
    val inversePrimaryDark = Color(0xFF804793)
    val surfaceDimDark = Color(0xFF141313)
    val surfaceBrightDark = Color(0xFF3A3938)
    val surfaceContainerLowestDark = Color(0xFF0F0E0E)
    val surfaceContainerLowDark = Color(0xFF1C1B1B)
    val surfaceContainerDark = Color(0xFF201F1F)
    val surfaceContainerHighDark = Color(0xFF2B2A29)
    val surfaceContainerHighestDark = Color(0xFF363434)

}